uniqush:
  container_name: uniqush-server
  image: beevelop/uniqush
  links:
    - redis
  restart: always

redis:
  container_name: uniqush-redis
  image: redis:alpine
  ports:
    - "9898:9898"
  restart: always
